import type { ThemeConfig } from './types'

export const PRESET_THEMES: ThemeConfig[] = [
  {
    id: 'minimal-corporate',
    name: 'Minimal Corporate',
    headerBg: '#1F2937',
    headerText: '#FFFFFF',
    headerFont: 'Calibri',
    headerFontSize: 11,
    headerBold: true,
    bodyFont: 'Calibri',
    bodyFontSize: 10.5,
    bodyText: '#1F2937',
    zebra: true,
    zebraColor: '#F3F4F6',
    borderStyle: 'thin',
    borderColor: '#D1D5DB',
    totalsBg: '#111827',
    totalsText: '#FFFFFF',
    globalAlignment: 'auto',
    accentColor: '#1F2937',
  },
  {
    id: 'tech-blue',
    name: 'Tech Blue',
    headerBg: '#0B4F9C',
    headerText: '#FFFFFF',
    headerFont: 'Segoe UI',
    headerFontSize: 11,
    headerBold: true,
    bodyFont: 'Segoe UI',
    bodyFontSize: 10.5,
    bodyText: '#0F172A',
    zebra: true,
    zebraColor: '#EAF2FD',
    borderStyle: 'thin',
    borderColor: '#BFDBFE',
    totalsBg: '#0B4F9C',
    totalsText: '#FFFFFF',
    globalAlignment: 'auto',
    accentColor: '#2563EB',
  },
  {
    id: 'executive-dark',
    name: 'Executive Dark',
    headerBg: '#0F0F12',
    headerText: '#E5B95C',
    headerFont: 'Georgia',
    headerFontSize: 11,
    headerBold: true,
    bodyFont: 'Georgia',
    bodyFontSize: 10.5,
    bodyText: '#1A1A1D',
    zebra: true,
    zebraColor: '#F1EFE9',
    borderStyle: 'thin',
    borderColor: '#C9A34E',
    totalsBg: '#0F0F12',
    totalsText: '#E5B95C',
    globalAlignment: 'auto',
    accentColor: '#E5B95C',
  },
  {
    id: 'finance-green',
    name: 'Finance Green',
    headerBg: '#065F46',
    headerText: '#FFFFFF',
    headerFont: 'Calibri',
    headerFontSize: 11,
    headerBold: true,
    bodyFont: 'Calibri',
    bodyFontSize: 10.5,
    bodyText: '#0F1F1A',
    zebra: true,
    zebraColor: '#E7F5EF',
    borderStyle: 'thin',
    borderColor: '#A7D9C5',
    totalsBg: '#043D2E',
    totalsText: '#FFFFFF',
    globalAlignment: 'auto',
    accentColor: '#0E9F6E',
  },
  {
    id: 'modern-purple',
    name: 'Modern Purple',
    headerBg: '#5B21B6',
    headerText: '#FFFFFF',
    headerFont: 'Poppins',
    headerFontSize: 11,
    headerBold: true,
    bodyFont: 'Poppins',
    bodyFontSize: 10.5,
    bodyText: '#241738',
    zebra: true,
    zebraColor: '#F1EBFB',
    borderStyle: 'thin',
    borderColor: '#DCC9F5',
    totalsBg: '#4C1D95',
    totalsText: '#FFFFFF',
    globalAlignment: 'auto',
    accentColor: '#7C3AED',
  },
  {
    id: 'sunset-coral',
    name: 'Sunset Coral',
    headerBg: '#B91C1C',
    headerText: '#FFFFFF',
    headerFont: 'Verdana',
    headerFontSize: 11,
    headerBold: true,
    bodyFont: 'Verdana',
    bodyFontSize: 10,
    bodyText: '#2A1212',
    zebra: true,
    zebraColor: '#FBEAEA',
    borderStyle: 'thin',
    borderColor: '#F3B6B6',
    totalsBg: '#7F1D1D',
    totalsText: '#FFFFFF',
    globalAlignment: 'auto',
    accentColor: '#EF4444',
  },
]

export function getThemeById(id: string): ThemeConfig | undefined {
  return PRESET_THEMES.find((t) => t.id === id)
}

export function cloneTheme(theme: ThemeConfig, overrides?: Partial<ThemeConfig>): ThemeConfig {
  return { ...theme, ...overrides }
}
